variables:
  buildConfiguration: 'Release'
  poolName: 'rac-pool'
  System.Debug: 'false'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  coreInfrastructureName: 'rac-core-infra-demo'
  webAppName: 'rac-fileupload-web-$(Environment.Name)'
  azFunctionName: 'rac-fileinflate-func-$(Environment.Name)'
  sendMailLogiAppName: 'rac-sendemail-$(Environment.Name)'
  azureSubscriptionName: 'DevTest'
  resourceGroupName: 'rac-demo-app'
  armTemplateParameters: '-coreInfrastructureName $(coreInfrastructureName) -webAppName $(webAppName) -azFunctionName $(azFunctionName) -sendMailLogiAppName $(sendMailLogiAppName)'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: '$(poolName)'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Provision Infrastructure'
      inputs:
        azureSubscription: $(azureSubscriptionName)
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        csmFile: $(System.DefaultWorkingDirectory)/templates/deployment/deployment.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/templates/deployment/deployment.parameters.json
        overrideParameters: '$(armTemplateParameters)'
        deploymentMode: 'Validation'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish ARM templates'
      inputs:
        path: $(System.DefaultWorkingDirectory)/templates
        artifact: templates


- stage: Deployment_Dev
  jobs:
  - deployment: deployment_dev
    displayName: 'Dev'
    pool: '$(poolName)'
    environment: 'dev'
    #condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              displayName: 'Provision Infrastructure'
              inputs:
                azureSubscription: $(azureSubscriptionName)
                resourceGroupName: '$(resourceGroupName)-$(Environment.Name)'
                location: 'West Europe'
                csmFile: $(Pipeline.Workspace)/templates/deployment/deployment.json
                csmParametersFile: $(Pipeline.Workspace)/templates/deployment/deployment.parameters.json
                overrideParameters: '$(armTemplateParameters)'

- stage: Deployment_Test
  jobs:
  - deployment: deployment_test
    displayName: 'Test'
    pool:
      vmImage: 'windows-2019'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              displayName: 'Provision Infrastructure'
              inputs:
                azureSubscription: $(azureSubscriptionName)
                resourceGroupName: '$(resourceGroupName)-$(Environment.Name)'
                location: 'West Europe'
                csmFile: $(Pipeline.Workspace)/templates/deployment/deployment.json
                csmParametersFile: $(Pipeline.Workspace)/templates/deployment/deployment.parameters.json
                overrideParameters: '$(armTemplateParameters)'

- stage: Deployment_Prod
  jobs:
  - deployment: deployment_prod
    displayName: 'Prod'
    pool: '$(poolName)'
    environment: 'prod'
    #condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              displayName: 'Provision Infrastructure'
              inputs:
                azureSubscription: $(azureSubscriptionName)
                resourceGroupName: '$(resourceGroupName)-$(Environment.Name)'
                location: 'West Europe'
                csmFile: $(Pipeline.Workspace)/templates/deployment/deployment.json
                csmParametersFile: $(Pipeline.Workspace)/templates/deployment/deployment.parameters.json
                overrideParameters: '$(armTemplateParameters)'
