variables:
  buildConfiguration: 'Release'
  poolName: 'rac-pool'
  System.Debug: 'false'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  projectName: 'rac-core-infra-demo'
  webAppName: '$(projectName)'
  azFunctionName: 'rac-fileinflate-func-$(Environment.Name)'
  azureSubscriptionName: 'DevTest'
  resourceGroupName: '$(WebAppName)'
  resourcename: '$(resourceGroupName)'
  armTemplateParameters: '-webAppName $(webAppName)-$(Environment.Name) -azFunctionName $(azFunctionName)'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: '$(poolName)'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Provision Infrastructure'
      inputs:
        azureSubscription: $(azureSubscriptionName)
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        csmFile: $(System.DefaultWorkingDirectory)/templates/deployment/deployment.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/templates/deployment/deployment.parameters.json
        overrideParameters: '$(armTemplateParameters)'
        deploymentMode: 'Validation'

    # - task: DotNetCoreCLI@2
    #   displayName: 'DotNet Core Restore'
    #   inputs:
    #     command: restore
    #     projects: '**/*.sln'

    # - task: DotNetCoreCLI@2
    #   displayName: 'DotNet Core Build'
    #   inputs:
    #     command: build
    #     projects: '**/*.sln'
    #     arguments: '--configuration $(buildConfiguration) --no-restore'

    # - task: DotNetCoreCLI@2
    #   displayName: 'DotNet Core Package WebApp'
    #   inputs:
    #     command: publish
    #     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    #     projects: '**/*.sln'
    #     zipAfterPublish: true

    # - task: DotNetCoreCLI@2
    #   displayName: 'DotNet Core Package Function'
    #   inputs:
    #     command: publish
    #     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    #     projects: '**/*Function.csproj'
    #     publishWebProjects: false
    #     zipAfterPublish: true

    # - task: PublishPipelineArtifact@1
    #   displayName: 'Publish Artifacts'
    #   inputs:
    #     path: $(build.artifactstagingdirectory)
    #     artifact: App

    - task: PublishPipelineArtifact@1
      displayName: 'Publish ARM templates'
      inputs:
        path: $(System.DefaultWorkingDirectory)/templates
        artifact: templates


- stage: Deployment_Dev
  jobs:
  - deployment: deployment_dev
    displayName: 'Dev'
    pool:
      vmImage: 'windows-2019'
    environment: 'dev'
    #condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deployment.yml

# - stage: Deployment_Test
#   jobs:
#   - deployment: deployment_test
#     displayName: 'Test'
#     pool:
#       vmImage: 'windows-2019'
#     environment: 'test'
#     condition: |
#       and(succeeded(),
#       eq(variables['Build.Reason'], 'PullRequest'))
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: deployment.yml
