steps:
  - task: DownloadPipelineArtifact@2

  - task: AzureResourceGroupDeployment@2
    displayName: 'Provision Infrastructure'
    inputs:
      azureSubscription: $(azureSubscriptionName)
      resourceGroupName: '$(resourceGroupName)-$(Environment.Name)'
      location: 'West Europe'
      csmFile: $(Pipeline.Workspace)/templates/deployment/deployment.json
      csmParametersFile: $(Pipeline.Workspace)/templates/deployment/deployment.parameters.json
      overrideParameters: '$(armTemplateParameters)'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Web Deploy'
    inputs:
      appType: webApp
      ConnectedServiceName: $(azureSubscriptionName)
      WebAppName: '$(WebAppName)-$(Environment.Name)'
      package: $(Pipeline.Workspace)/app/*Web.zip

  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Functon Deploy'
    inputs:
      appType: functionApp
      ConnectedServiceName: $(azureSubscriptionName)
      WebAppName: '$(WebAppName)-func-$(Environment.Name)'
      package: $(Pipeline.Workspace)/app/*Function.zip
